/* Formatted on 24.08.2022 15:20:51 (QP5 v5.252.13127.32867) */
-- EXCEPTION

CREATE OR REPLACE FUNCTION DIVISION (A NUMBER, B NUMBER)
   RETURN NUMBER
IS
   C   NUMBER;
BEGIN
   C := A / B;
   RETURN (C);
END;


DECLARE
   D   NUMBER;
BEGIN
   D := DIVISION (10, 2);
   DBMS_OUTPUT.PUT_LINE (D);
/*
EXCEPTION WHEN ZERO_DIVIDE THEN
    DBMS_OUTPUT.PUT_LINE(SQLERRM);
*/
END;

--

SELECT * FROM departments;

DESC DEPARTMENTS;


CREATE OR REPLACE FUNCTION BOLUM_ADI (P_BOLUMNO IN NUMBER)
   RETURN VARCHAR2
IS
   WBOLUM_ADI   VARCHAR2 (30);
BEGIN
   SELECT DEPARTMENT_NAME
     INTO WBOLUM_ADI
     FROM departments
    WHERE department_id = P_BOLUMNO;

   RETURN (WBOLUM_ADI);
EXCEPTION
   WHEN NO_DATA_FOUND
   THEN
      RETURN (P_BOLUMNO || ' NOLU BOLUM BULUNAMADI');
END;

DECLARE
   WADI   VARCHAR2 (30);
BEGIN
   WADI := BOLUM_ADI (2);
   DBMS_OUTPUT.PUT_LINE (WADI);
END;