
BEGIN
DBMS_OUTPUT.PUT_LINE('Hello world! ');
END;

DECLARE
	WMEssage VARCHAR2(50);
BEGIN
	WMEssage := 'Merhaba pl/sql! ';
	DBMS_OUTPUT.PUT_LINE(WMEssage);
END;

SET SERVEROUTPUT ON;

-- ALTER USER HR IDENTIFIED BY HR  ACCOUNT UNLOCK;