-- SEQUENCE (CURRVAL, NEXTVAL)

SET SERVEROUTPUT ON;
DESC REGIONS;

SELECT * FROM REGIONS;

CREATE SEQUENCE TEST_SEQ START WITH 5 INCREMENT BY 1;

SELECT TEST_SEQ.CURRVAL FROM DUAL;

DECLARE
 seq_num NUMBER;
BEGIN
    seq_num := TEST_SEQ.NEXTVAL;
    INSERT INTO REGIONS(REGION_ID, REGION_NAME) 
            VALUES (seq_num, 'Avustralya');
 -- ROLLBACK;
    
    seq_num := TEST_SEQ.CURRVAL;
    UPDATE REGIONS SET REGION_NAME = 'Antartika' WHERE REGION_ID = seq_num;
    
    commit;
END;