-- FOR LOOP

SET SERVEROUTPUT ON;

BEGIN
   -- FOR SAYAC IN REVERSE 1..5 LOOP
   FOR SAYAC IN 1 .. 5
   LOOP
      -- EXIT WHEN SAYAC = 3;
      -- CONTINUE  WHEN SAYAC = 3;
      DBMS_OUTPUT.PUT_LINE ('SAYAC = ' || SAYAC);
   END LOOP;
END;
/

DECLARE
   FACTORIAL   NUMBER := 1;
BEGIN
   FOR SAYAC IN 1 .. 5
   LOOP
      FACTORIAL := FACTORIAL * SAYAC;
   END LOOP;

   DBMS_OUTPUT.PUT_LINE ('5! = ' || FACTORIAL);
END;