-- CURSORs, --IMPLICIT CURSOR --SQL%FOUND, SQL%NOTFOUND, SQL%ROWCOUNT
SET SERVEROUTPUT ON;
/
DECLARE
    REC_EMP EMPLOYEES2%ROWTYPE;
BEGIN
    SELECT * INTO REC_EMP FROM EMPLOYEES2 WHERE EMPLOYEE_ID = 100;
    
    IF SQL%FOUND THEN
        DBMS_OUTPUT.PUT_LINE ('KAYIT VAR, ' || SQL%ROWCOUNT);
    ELSE
        DBMS_OUTPUT.PUT_LINE ('KAYIT YOK');
    END IF;
    
    IF SQL%NOTFOUND THEN
        DBMS_OUTPUT.PUT_LINE ('KAYIT YOK 1');
    ELSE
        DBMS_OUTPUT.PUT_LINE ('KAYIT VAR 1, ' || SQL%ROWCOUNT);
    END IF;
    
    EXCEPTION WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE ('KAYIT YOK 2');    
    
END;