SET SERVEROUTPUT ON;
/
DESC EMPLOYEES2;
/
SELECT DEPARTMENT_ID, COUNT(*) 
FROM EMPLOYEES2 
GROUP BY DEPARTMENT_ID;

/
DECLARE
    REC_EMP EMPLOYEES2%ROWTYPE;
BEGIN
    UPDATE EMPLOYEES2 SET SALARY = SALARY * 1.2 WHERE DEPARTMENT_ID = 500;
    
    IF SQL%FOUND THEN
        DBMS_OUTPUT.PUT_LINE (SQL%ROWCOUNT ||' personnel updated');
    ELSE
        DBMS_OUTPUT.PUT_LINE ('Can not updated');
    END IF;
    
    IF SQL%NOTFOUND THEN
        DBMS_OUTPUT.PUT_LINE ('Can not updated 1');
    ELSE
        DBMS_OUTPUT.PUT_LINE (SQL%ROWCOUNT ||' personnel updated 1');
    END IF;  
    
END;