CREATE OR REPLACE TYPE t_nested IS TABLE OF VARCHAR2(30);
/
CREATE OR REPLACE TYPE t_varray IS VARRAY(5) OF NUMBER(17,2);
/
CREATE OR REPLACE TYPE t_assoc_array_num IS TABLE OF NUMBER INDEX BY PLS_INTEGER;
/
DROP TYPE t_assoc_array_num;
/
-- ALL_TYPES, DBA_TYPES, USER_TYPES

SELECT * FROM USER_TYPES;
/
SELECT * FROM USER_SOURCE WHERE TYPE = 'TYPE';